CREATE TABLE Portfolios (
  port_id SERIAL PRIMARY KEY,
  user_id INT NOT NULL,
  port_name TEXT NOT NULL,
  cash_dep NUMERIC(12,2) NOT NULL DEFAULT 0.00,
  reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);
